# Generated by Django 3.0.6 on 2020-09-29 14:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('iso2', models.CharField(max_length=2, unique=True, verbose_name='ISO 3166-1 Alpha 2 Name')),
                ('iso3', models.CharField(max_length=3, unique=True, verbose_name='ISO 3166-1 Alpha 3 Name')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Country Name')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'ordering': ('iso2', 'name'),
            },
        ),
        migrations.CreateModel(
            name='SanctionedCountry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('us_sanctions', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('us_sanction_comments', models.TextField(blank=True, null=True)),
                ('eu_sanctions', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('eu_sanction_comments', models.TextField(blank=True, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='country.Country')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
