# Generated by Django 3.0.6 on 2020-06-10 15:24

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=255, populate_from=['name'])),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_type',
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.ManyToManyField(to='core.QuestionType'),
        ),
    ]
