# Generated by Django 3.0.6 on 2020-06-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200610_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('SOCIAL', 'Social'), ('ENVIRONMENT', 'Environmental'), ('GOVERNANCE', 'Governance')], max_length=32),
        ),
    ]
