# Generated by Django 3.0.6 on 2020-06-22 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riskfactor', '0025_auto_20200618_1045'),
        ('company', '0011_companyassessment_documentquestionanswerset_managementquestionanswerset'),
        ('core', '0005_auto_20200615_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('SOCIAL', 'Social'), ('ENVIRONMENT', 'Environmental'), ('GOVERNANCE', 'Governance')], max_length=32)),
                ('text', models.TextField()),
                ('yes_score', models.PositiveIntegerField(default=1)),
                ('no_score', models.PositiveIntegerField(default=0)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.Company')),
                ('trigger_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.DocumentQuestion')),
            ],
        ),
        migrations.CreateModel(
            name='ManagementQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('SOCIAL', 'Social'), ('ENVIRONMENT', 'Environmental'), ('GOVERNANCE', 'Governance')], max_length=32)),
                ('text', models.TextField()),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.Company')),
                ('riskfactors', models.ManyToManyField(related_name='questions', to='riskfactor.RiskDataSet')),
            ],
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='QuestionType',
        ),
    ]
