# Generated by Django 3.0.6 on 2020-07-08 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200622_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='managementquestion',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
