# Generated by Django 3.0.6 on 2020-07-10 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_managementquestion_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentquestion',
            name='is_answerable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='documentquestion',
            name='notes',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
