# Generated by Django 3.0.6 on 2020-07-10 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200710_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentquestion',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
