# Generated by Django 3.0.6 on 2020-07-10 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_documentquestion_display_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentquestion',
            name='no_score',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='documentquestion',
            name='yes_score',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
