# Generated by Django 3.0.6 on 2020-07-10 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200710_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentquestion',
            name='notes',
        ),
    ]
