# Generated by Django 3.0.6 on 2020-07-17 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_documentquestion_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Threshold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, unique=True)),
                ('lower_bound', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('upper_bound', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
            ],
        ),
    ]
