# Generated by Django 3.0.6 on 2020-07-23 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentquestion',
            name='pdf_display_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='documentquestion',
            name='pdf_display_order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
