# Generated by Django 3.0.6 on 2020-07-23 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_sanctionedcountry'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentquestion',
            name='is_best_practice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documentquestion',
            name='is_key',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documentquestion',
            name='is_market_leading',
            field=models.BooleanField(default=False),
        ),
    ]
