# Generated by Django 3.0.6 on 2020-07-27 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200723_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='managementquestion',
            name='pdf_display_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='managementquestion',
            name='pdf_display_order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
