# Generated by Django 3.0.6 on 2020-08-17 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20200727_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='pdfContactDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='address')),
                ('post_code', models.CharField(blank=True, max_length=10, verbose_name='post code')),
                ('phone', models.CharField(max_length=40, verbose_name='phone')),
                ('email', models.EmailField(max_length=255)),
            ],
        ),
    ]
