# Generated by Django 3.0.6 on 2020-08-25 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_delete_pdfcontactdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanctionedcountry',
            name='eu_sanctions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sanctionedcountry',
            name='notes',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='sanctionedcountry',
            name='us_sanctions',
            field=models.BooleanField(default=False),
        ),
    ]
