# Generated by Django 3.0.6 on 2020-08-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20200825_1637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sanctionedcountry',
            old_name='notes',
            new_name='eu_sanction_comments',
        ),
        migrations.AddField(
            model_name='sanctionedcountry',
            name='us_sanction_comments',
            field=models.TextField(null=True),
        ),
    ]
