# Generated by Django 3.0.6 on 2020-08-27 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20200827_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanctionedcountry',
            name='eu_sanctions',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')]),
        ),
        migrations.AlterField(
            model_name='sanctionedcountry',
            name='us_sanction_comments',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sanctionedcountry',
            name='us_sanctions',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')]),
        ),
    ]
