# Generated by Django 3.0.6 on 2020-08-28 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20200827_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanctionedcountry',
            name='eu_sanction_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sanctionedcountry',
            name='us_sanction_comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
