# Generated by Django 3.0.6 on 2020-09-22 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20200828_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='threshold',
            name='colour',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
