# Generated by Django 2.0.1 on 2019-11-04 11:15

from django.db import migrations
from django.db.utils import OperationalError

from pprint import pprint

def delete_owned_management_questions(apps, schema_editor):
    management_questions = apps.get_model("core", "ManagementQuestion")
    management_questions.objects.filter(company__isnull=False).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20200930_1021'),
    ]

    operations = [
        migrations.RunPython(delete_owned_management_questions, reverse_code=migrations.RunPython.noop),
    ]