# Generated by Django 3.0.6 on 2020-10-07 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_delete_company_owned_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managementquestion',
            name='enabled',
        ),
    ]
