# Generated by Django 3.0.6 on 2020-10-26 10:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_managementquestion_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='InherentRiskThreshold',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('text', models.CharField(max_length=255, unique=True)),
                ('lower_bound', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('upper_bound', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('colour', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
