# Generated by Django 3.0.6 on 2021-05-18 15:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_inherentriskthreshold'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('endpoint', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
