# Generated by Django 3.0.6 on 2021-06-09 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentquestion',
            name='is_required',
            field=models.BooleanField(default=False),
        ),
    ]
