# Generated by Django 3.0.6 on 2021-06-11 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_documentquestion_is_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='inherentriskthreshold',
            name='text_in_sentence',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='threshold',
            name='text_in_sentence',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
