# Generated by Django 3.0.6 on 2021-06-17 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20210611_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='endpoint',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
