# Generated by Django 4.0.4 on 2022-06-16 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20210617_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentquestion',
            name='is_key_policy',
            field=models.BooleanField(default=False),
        ),
    ]
