# Generated by Django 3.0.6 on 2020-08-18 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdfcontactdetail',
            name='address',
        ),
        migrations.AddField(
            model_name='pdfcontactdetail',
            name='address_line_1',
            field=models.CharField(default=' ', max_length=255, verbose_name='Address line 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pdfcontactdetail',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address line 2'),
        ),
        migrations.AddField(
            model_name='pdfcontactdetail',
            name='address_line_3',
            field=models.CharField(default=' ', max_length=255, verbose_name='Town/City'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pdfcontactdetail',
            name='address_line_4',
            field=models.CharField(default=' ', max_length=255, verbose_name='County'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pdfcontactdetail',
            name='post_code',
            field=models.CharField(max_length=10, verbose_name='post code'),
        ),
    ]
