# Generated by Django 3.0.6 on 2020-09-30 10:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_auto_20200818_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfcontactdetail',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
