# Generated by Django 3.0.6 on 2020-06-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200608_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='force_password_change',
            field=models.BooleanField(blank=True, default=False, verbose_name='Force password change?'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hear_about_us',
            field=models.BooleanField(blank=True, default=False, verbose_name='How Did You Hear About Us?'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='receive_anthesis_newsletter',
            field=models.BooleanField(blank=True, default=False, verbose_name='I wish to receive the Anthesis Group newsletter?'),
        ),
    ]
