# Generated by Django 3.0.6 on 2020-06-19 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200618_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='receive_anthesis_newsletter',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='hear_about_us',
            field=models.TextField(blank=True, null=True, verbose_name='How Did You Hear About Us?'),
        ),
    ]
