"""
Django settings for acn project.

Generated by "django-admin startproject" using Django 2.0.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os
import hashids
import platform
from datetime import timedelta


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'SECRET_KEY')

# SECURITY WARNING: don"t run with debug turned on in production!
HOSTNAME = os.environ.get('HOST_HOSTNAME', 'dev').lower()
DEBUG = os.environ.get('DEBUG', 'True')
DEBUG = True if DEBUG == 'True' else False
DEBUG = False if HOSTNAME in ('live', "staging", "staging4") else DEBUG

if DEBUG is False:
    COMPRESS_ENABLED = True
    CSRF_COOKIE_HTTPONLY = True
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True

    # SENTRY for live and staging only
    import sentry_sdk
    from sentry_sdk.integrations.django import DjangoIntegration
    DSN_KEY = os.environ.get('DSN_KEY', None)

    if DSN_KEY:
        sentry_sdk.init(
            dsn=DSN_KEY,
            integrations=[DjangoIntegration()]
        )

HASHER = hashids.Hashids(salt=SECRET_KEY, min_length=16, alphabet="abcdefghijklmnopqrstuvwxyz0123456789")

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    "riskhorizon-app-01-staging3.azurewebsites.net",
    "riskhorizon-app-01.azurewebsites.net",
    "staging3.risk-horizon.com",
    "staging4.risk-horizon.com",
    "app.risk-horizon.com",
]

CSRF_TRUSTED_ORIGINS = [
    "http://127.0.0.0",
    "http://localhost",
    "https://riskhorizon-app-01-staging3.azurewebsites.net",
    "https://riskhorizon-app-01.azurewebsites.net",
    "https://staging3.risk-horizon.com",
    "https://staging4.risk-horizon.com",
    "https://app.risk-horizon.com",
]

INSTALLED_APPS = [
    # Django
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    "django.contrib.humanize",
    "django.contrib.flatpages",

    # 3rd Party
    "django_extensions",
    "crispy_forms",
    "ckeditor",
    "ckeditor_uploader",
    "accounts",
    "allauth",
    "allauth.account",
    "compressor",
    # "easy_thumbnails",
    "sorl.thumbnail",

    "core",
    "staff_admin",
    "riskfactor",
    "dashboard",
    "portfolio",
    "screening",
    "company",
    "geo",
    "report",
    "users",
    "country",
    "kpi",

    'axes',
    "anymail"
]

SITE_ID = 1

AUTH_USER_MODEL = 'users.User'

AUTHENTICATION_BACKENDS = (
    # Needed to login by username in Django admin, regardless of `allauth`
    'axes.backends.AxesBackend',
    'django.contrib.auth.backends.ModelBackend',

    # `allauth` specific authentication methods, such as login by e-mail
    'allauth.account.auth_backends.AuthenticationBackend',
)

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "axes.middleware.AxesMiddleware",
    "core.middleware.RedirectMiddleware"
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            os.path.join(BASE_DIR, "core", "templates"),
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "core.middleware.template_context",
                "core.middleware.company_assessment_template_context"
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ.get('MYSQL_DATABASE'),
        'USER': os.environ.get('MYSQL_USER'),  # Not used with sqlite3.
        'PASSWORD': os.environ.get('MYSQL_PASSWORD'),
        'HOST': os.environ.get('MYSQL_HOST') if os.environ.get('MYSQL_HOST') != '' else '127.0.0.1' if platform.system() == "Windows" else 'database',
        'PORT': '3306',
        "OPTIONS": {
            "charset": "utf8mb4",
            "init_command": "SET foreign_key_checks = 0;",
        },
        'TEST': {
            'ENGINE': 'django.db.backends.sqlite3',
        },
    }
}

# Password validation
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
    'django.contrib.auth.hashers.BCryptPasswordHasher',
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = "en-gb"
TIME_ZONE = "UTC"
USE_I18N = False
USE_L10N = False
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "core", "static")

GEOIP_PATH = os.path.join(BASE_DIR, "core", "geoip")
STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    # other finders..
    'compressor.finders.CompressorFinder',
)
MEDIA_ROOT = os.path.join(BASE_DIR, "uploads")
MEDIA_URL = "/uploads/"

CRISPY_FAIL_SILENTLY = not DEBUG
CRISPY_TEMPLATE_PACK = 'bootstrap4'

LOGIN_REDIRECT_URL = "/dashboard/"
ACCOUNT_EMAIL_CONFIRMATION_AUTHENTICATED_REDIRECT_URL = "/dashboard/"
ACCOUNT_AUTHENTICATION_METHOD = "email"
ACCOUNT_CONFIRM_EMAIL_ON_GET = True
ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 10
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION = "mandatory"
ACCOUNT_EMAIL_SUBJECT_PREFIX = ""
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = False
ACCOUNT_SESSION_REMEMBER = None
ACCOUNT_USER_DISPLAY = lambda user: user.get_full_name() or user.email
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_FORMS = {
    "login": "core.auth.MyAccountLogIn",
    "signup": "core.auth.MyAccountSignUp",
    'reset_password': 'core.auth.MyResetPasswordForm',
    'change_password': 'core.auth.MyChangePasswordForm',
}
ACCOUNT_LOGOUT_ON_GET = True
ACCOUNT_LOGIN_ATTEMPTS_LIMIT = None
AXES_FAILURE_LIMIT = 6
AXES_COOLOFF_TIME = timedelta(minutes=15)
AXES_USERNAME_FORM_FIELD = 'login'
AXES_RESET_ON_SUCCESS = True
AXES_LOCKOUT_TEMPLATE = "lockout.html"

SESSION_COOKIE_AGE = 36000

CKEDITOR_UPLOAD_PATH = "user_uploads/"
CKEDITOR_ALLOW_NONIMAGE_FILES = False
CKEDITOR_RESTRICT_BY_USER = True
CKEDITOR_BROWSE_SHOW_DIRS = True
CKEDITOR_CONFIGS = {
    'default': {
        'height': 300,
        'width': "100%",
        'extraPlugins': "autolink,embedsemantic,clipboard,uploadimage,pastefromword,smiley,specialchar,table,tableresize,tabletools,mentions",
        'removePlugins': "elementspath",
        'toolbar': 'Custom',
        'toolbar_Custom': [
            ['Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord', '-', 'Undo', 'Redo'],
            ['Find', 'Replace', '-', 'SelectAll'],
            ['Styles', 'Format', 'TextColor', 'BGColor'],
            ['Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript', '-', 'RemoveFormat'],
            ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock'],
            ['Link', 'Unlink'],
            ['Table', 'Image', 'Smiley', 'SpecialChar']
        ]
    },
}

GRAPH_MODELS = {
    'all_applications': True,
    'group_models': True,
}
THUMBNAIL_PRESERVE_FORMAT = True
THUMBNAIL_HIGH_RESOLUTION = True

THUMBNAIL_PROCESSORS = (
    'easy_thumbnails.processors.colorspace',
    'easy_thumbnails.processors.autocrop',
    # 'easy_thumbnails.processors.scale_and_crop',
    'filer.thumbnail_processors.scale_and_crop_with_subject_location',
    'easy_thumbnails.processors.filters',
)

SENDFILE_ROOT = os.path.join(BASE_DIR, "uploads")
SENDFILE_URL = "/uploads"

SLACK_API_TOKEN = os.environ.get("SLACK_API_TOKEN", None)
SLACK_POSTING_ENABLED = True

DEFAULT_TIMEZONE = "Europe/London"
ENABLE_HOME_MENU = False

ANYMAIL = {
    # (exact settings here depend on your ESP...)
    "SENDGRID_API_KEY": os.environ.get("SENDGRID_API_KEY", None),
    #"MAILGUN_SENDER_DOMAIN": 'mail.risk-horizon.com',  # your Mailgun domain
}

if DEBUG:
    SIGN_UP_NOTIFICATION_TO_ADDRESS = 'test-notificatiom@test.com'
    # EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    EMAIL_BACKEND = 'anymail.backends.sendgrid.EmailBackend'
    SENDFILE_BACKEND = "sendfile.backends.development"
    DEFAULT_FROM_EMAIL = 'noreply@staging3.risk-horizon.com'

    AUTH_PASSWORD_VALIDATORS = [
        {
            'NAME': 'core.password_validation.PasswordValidator',
        },
    ]

if not DEBUG:
    AUTH_PASSWORD_VALIDATORS = [
        {
            'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
        },
        {
            'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
            'OPTIONS': {
                'min_length': 12,
            }
        },
        {
            'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
        },
        {
            'NAME': 'core.password_validation.PasswordValidator',
        },
    ]

if HOSTNAME in ('live', "staging", "staging4"):
    EMAIL_BACKEND = 'anymail.backends.sendgrid.EmailBackend'
    SENDFILE_BACKEND = "sendfile.backends.nginx"

if HOSTNAME == "staging":
    DEFAULT_FROM_EMAIL = "noreply@staging3.risk-horizon.com"
    SIGN_UP_NOTIFICATION_TO_ADDRESS = None
if HOSTNAME == "staging4":
    DEFAULT_FROM_EMAIL = "noreply@staging4.risk-horizon.com"
    SIGN_UP_NOTIFICATION_TO_ADDRESS = 'esg@landmark.co.uk'
if HOSTNAME == "live":
    DEFAULT_FROM_EMAIL = "noreply@app.risk-horizon.com"
    SIGN_UP_NOTIFICATION_TO_ADDRESS = 'esg@landmark.co.uk'

# In minutes
ASSESSMENT_SESSION_TIME = os.environ.get('ASSESSMENT_SESSION_TIME', 30)

SASB_API_KEY = os.environ.get('SASB_API_KEY', None)
DEFAULT_AUTO_FIELD='django.db.models.AutoField'
