# Generated by Django 3.0.6 on 2020-06-08 12:01

import company.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('country', '0001_initial'),
        ('riskfactor', '0004_auto_20200529_0954'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='organisation name')),
                ('organisation_type', models.CharField(max_length=40)),
                ('address', models.TextField(verbose_name='address')),
                ('phone', models.CharField(max_length=40, verbose_name='phone')),
                ('sector', models.CharField(blank=True, max_length=40, verbose_name='sector')),
                ('city', models.CharField(blank=True, max_length=40, verbose_name='city')),
                ('post_code', models.CharField(blank=True, max_length=10, verbose_name='post code')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='country.Country', verbose_name='Country')),
                ('default_riskfactors', models.ManyToManyField(blank=True, help_text='To have only a subset of riskfactors initially "checked" in an assessment, select them here.<br/>Leave none (or all of them) selected to have them all checked<br/>', to='riskfactor.RiskDataSet', verbose_name='Default Selected Riskfactors')),
                ('primary_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'companies',
            },
        ),
        migrations.CreateModel(
            name='CompanyEmailDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=63, unique=True, validators=[company.models.CompanyEmailDomain.validate_domain])),
                ('enabled', models.BooleanField(blank=True, default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Company')),
            ],
        ),
    ]
