# Generated by Django 3.0.6 on 2020-06-10 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riskfactor', '0004_auto_20200529_0954'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('SOCIAL', 'Social risk management measures'), ('ENVIRONMENT', 'Environmental risk management measures'), ('GOVERNANCE', 'Governance measures')], max_length=32)),
                ('text', models.TextField()),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.Company')),
                ('riskfactors', models.ManyToManyField(related_name='questions', to='riskfactor.RiskDataSet')),
            ],
        ),
    ]
