# Generated by Django 3.0.6 on 2020-06-10 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MANAGEMENT', 'Management question'), ('DOCUMENT', 'Document question')], default='MANAGEMENT', max_length=255),
            preserve_default=False,
        ),
    ]
