# Generated by Django 3.0.6 on 2020-06-10 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_question_question_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
