# Generated by Django 3.0.6 on 2020-06-17 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_industry'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='user_signup',
            field=models.CharField(choices=[('X', 'Not allowed - new employees can only be added in the company admin area'), ('A', 'Allowed - employees can register, but must be accepted by an admin')], default='A', max_length=1, verbose_name='User sign-up configuration'),
        ),
    ]
