# Generated by Django 3.0.6 on 2020-06-17 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_company_user_signup'),
    ]

    operations = [
        migrations.AddField(
            model_name='industry',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='industry',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
