# Generated by Django 3.0.6 on 2020-06-18 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_companyfund'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyFund',
        ),
    ]
