# Generated by Django 3.0.6 on 2020-06-22 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_companyfund'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAssessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(max_length=255, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField()),
                ('status', models.CharField(choices=[('C', 'Completed'), ('I', 'Incomplete'), ('W', 'Waiting for report')], default='I', max_length=1)),
                ('company_name', models.CharField(max_length=255)),
                ('company_headquarters', models.CharField(blank=True, max_length=255, null=True)),
                ('company_employee_count', models.PositiveIntegerField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('company_description', models.TextField(blank=True, null=True)),
                ('risk_summary', models.TextField(blank=True, null=True)),
                ('issue_description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentQuestionAnswerSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('X', 'No Evidence')], default='N', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ManagementQuestionAnswerSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('insufficient', models.BooleanField(blank=True, default=True)),
                ('priority', models.BooleanField(blank=True, default=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.CompanyAssessment')),
            ],
        ),
    ]
