# Generated by Django 3.0.6 on 2020-06-22 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200622_0859'),
        ('country', '0001_initial'),
        ('company', '0011_companyassessment_documentquestionanswerset_managementquestionanswerset'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('riskfactor', '0025_auto_20200618_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='managementquestionanswerset',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ManagementQuestion'),
        ),
        migrations.AddField(
            model_name='documentquestionanswerset',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.CompanyAssessment'),
        ),
        migrations.AddField(
            model_name='documentquestionanswerset',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.DocumentQuestion'),
        ),
        migrations.AddField(
            model_name='companyassessment',
            name='company_fund',
            field=models.ManyToManyField(blank=True, related_name='funds', to='company.CompanyFund'),
        ),
        migrations.AddField(
            model_name='companyassessment',
            name='countries',
            field=models.ManyToManyField(blank=True, related_name='countries', to='country.Country'),
        ),
        migrations.AddField(
            model_name='companyassessment',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companyassessment',
            name='industries',
            field=models.ManyToManyField(blank=True, to='company.Industry'),
        ),
        migrations.AddField(
            model_name='companyassessment',
            name='issues',
            field=models.ManyToManyField(blank=True, related_name='issues', to='riskfactor.IndustryRiskDataSet'),
        ),
        migrations.AddField(
            model_name='companyassessment',
            name='material_risks',
            field=models.ManyToManyField(blank=True, related_name='risks', to='riskfactor.IndustryRiskDataSet'),
        ),
    ]
