# Generated by Django 3.0.6 on 2020-06-22 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_auto_20200622_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyassessment',
            name='date_updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
