# Generated by Django 3.0.6 on 2020-06-25 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_auto_20200622_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyassessment',
            name='company_employee_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of employees'),
        ),
        migrations.AlterField(
            model_name='companyassessment',
            name='company_headquarters',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Headquarters'),
        ),
        migrations.AlterField(
            model_name='companyassessment',
            name='company_name',
            field=models.CharField(max_length=255, verbose_name='Company Name'),
        ),
    ]
