# Generated by Django 3.0.6 on 2020-06-25 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0014_auto_20200625_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyassessment',
            name='report_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Report Name'),
        ),
    ]
