# Generated by Django 3.0.6 on 2020-06-28 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskfactor', '0025_auto_20200618_1045'),
        ('company', '0015_auto_20200625_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyassessment',
            name='material_risks',
            field=models.ManyToManyField(blank=True, related_name='risks', to='riskfactor.RiskDataSet'),
        ),
    ]
