# Generated by Django 3.0.6 on 2020-07-06 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0016_auto_20200628_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyassessment',
            name='deal_type',
            field=models.CharField(choices=[('T', 'Target Company'), ('N', 'Not Acquired'), ('P', 'Portfolio Company'), ('E', 'Exited')], default='N', max_length=1),
        ),
    ]
