# Generated by Django 3.0.6 on 2020-07-08 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0017_companyassessment_deal_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyassessment',
            name='references',
            field=models.TextField(blank=True, null=True),
        ),
    ]
