# Generated by Django 3.0.6 on 2020-07-10 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0018_companyassessment_references'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentquestionanswerset',
            name='notes',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
