# Generated by Django 3.0.6 on 2020-07-14 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0019_documentquestionanswerset_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyassessment',
            name='issues',
        ),
    ]
