# Generated by Django 3.0.6 on 2020-07-14 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskfactor', '0025_auto_20200618_1045'),
        ('company', '0020_remove_companyassessment_issues'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyassessment',
            name='issues',
            field=models.ManyToManyField(blank=True, related_name='issues', to='riskfactor.RiskDataSet'),
        ),
    ]
