# Generated by Django 3.0.6 on 2020-07-15 08:59

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0021_companyassessment_issues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyassessment',
            name='issue_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
