# Generated by Django 3.0.6 on 2020-07-15 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0022_auto_20200715_0859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyassessment',
            name='issue_description',
        ),
        migrations.AddField(
            model_name='companyassessment',
            name='issue_extra_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AssessmentIssueRecommendations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.CharField(max_length=255)),
                ('recommendation', models.TextField()),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.CompanyAssessment')),
            ],
        ),
    ]
