# Generated by Django 3.0.6 on 2020-07-21 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0023_auto_20200715_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='reference',
            field=models.CharField(default=' ', max_length=255, verbose_name='Company reference'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyassessment',
            name='client_reference',
            field=models.CharField(default=' ', max_length=255, verbose_name='Company reference'),
            preserve_default=False,
        ),
    ]
