# Generated by Django 3.0.6 on 2020-07-21 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0024_auto_20200721_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyassessment',
            name='report_reference',
            field=models.CharField(default=' ', max_length=255, verbose_name='Report reference'),
            preserve_default=False,
        ),
    ]
