# Generated by Django 3.0.6 on 2020-07-24 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0025_companyassessment_report_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyassessment',
            name='client_reference',
            field=models.CharField(max_length=255),
        ),
    ]
