# Generated by Django 3.0.6 on 2020-08-06 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20200727_1500'),
        ('company', '0026_auto_20200724_1124'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='documentquestionanswerset',
            unique_together={('assessment', 'question')},
        ),
        migrations.AlterUniqueTogether(
            name='managementquestionanswerset',
            unique_together={('assessment', 'question')},
        ),
    ]
