# Generated by Django 3.0.6 on 2020-08-26 08:11

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0027_auto_20200806_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyassessment',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=255, populate_from=['report_name'], verbose_name='Assessment Code'),
        ),
    ]
