# Generated by Django 2.0.1 on 2019-11-04 11:15

from django.db import migrations
from django.db.utils import OperationalError

def generate_assessment_slugs(apps, schema_editor):

    assessments = apps.get_model("company", "CompanyAssessment")

    for assessment in assessments.objects.all():
        assessment.save()

class Migration(migrations.Migration):

    dependencies = [
        ('company', '0028_companyassessment_slug'),
    ]

    operations = [
        migrations.RunPython(generate_assessment_slugs, reverse_code=migrations.RunPython.noop),
    ]