# Generated by Django 3.0.6 on 2020-08-28 08:49

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0029_generate_assessment_slugs'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyfund',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=255, populate_from=['name']),
        ),
    ]
