# Generated by Django 2.0.1 on 2019-11-04 11:15

from django.db import migrations
from django.db.utils import OperationalError

def generate_fund_slugs(apps, schema_editor):
    funds = apps.get_model("company", "CompanyFund")

    for fund in funds.objects.all():
        fund.save()

class Migration(migrations.Migration):

    dependencies = [
        ('company', '0030_companyfund_slug'),
    ]

    operations = [
        migrations.RunPython(generate_fund_slugs, reverse_code=migrations.RunPython.noop),
    ]