# Generated by Django 3.0.6 on 2020-09-21 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0031_generate_fund_slugs'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='account_manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_manager', to=settings.AUTH_USER_MODEL),
        ),
    ]
