# Generated by Django 3.0.6 on 2020-09-23 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0032_company_account_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='account_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_manager', to=settings.AUTH_USER_MODEL),
        ),
    ]
