# Generated by Django 3.0.6 on 2020-09-28 13:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0043_company_assessment_pk_to_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyassessment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
