# Generated by Django 3.0.6 on 2020-09-29 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('country', '__first__'),
        ('company', '0044_auto_20200928_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='country.Country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='companyassessment',
            name='countries',
            field=models.ManyToManyField(blank=True, related_name='countries', to='country.Country'),
        ),
    ]
