# Generated by Django 3.0.6 on 2020-10-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_managementquestion_enabled'),
        ('company', '0045_auto_20200929_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyassessment',
            name='added_management_questions',
            field=models.ManyToManyField(blank=True, related_name='added_management_questions', to='core.ManagementQuestion'),
        ),
        migrations.AddField(
            model_name='companyassessment',
            name='deleted_management_questions',
            field=models.ManyToManyField(blank=True, related_name='deleted_management_questions', to='core.ManagementQuestion'),
        ),
    ]
