# Generated by Django 3.0.6 on 2020-10-26 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0047_auto_20201009_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industry',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Insight paragraph'),
        ),
        migrations.AlterField(
            model_name='industry',
            name='short_description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
