# Generated by Django 3.0.6 on 2020-11-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0048_auto_20201026_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentquestionanswerset',
            name='notes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
