# Generated by Django 3.0.6 on 2020-12-21 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0049_auto_20201113_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyassessment',
            name='company_fund',
        ),
        migrations.AddField(
            model_name='companyassessment',
            name='company_fund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funds', to='company.CompanyFund'),
        ),
    ]
