# Generated by Django 3.0.6 on 2021-05-18 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_permission'),
        ('company', '0050_auto_20201221_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='core.Permission'),
        ),
    ]
