# Generated by Django 3.0.6 on 2021-05-19 12:37

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0051_auto_20210519_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='industrytype',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=255, populate_from=['name']),
        ),
    ]
