# Generated by Django 3.0.6 on 2021-05-21 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0052_industrytype_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyassessment',
            name='is_latest',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='companyassessment',
            name='report_name',
            field=models.CharField(max_length=255, verbose_name='Report Name'),
        ),
    ]
