# Generated by Django 3.0.6 on 2021-05-20 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0052_industrytype_slug'),
        ('company', '0051_company_permissions'),
    ]

    operations = [
    ]
