# Generated by Django 3.0.6 on 2021-05-24 10:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0052_industrytype_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='SasbCompanyLookup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='organisation name')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Industry')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
