# Generated by Django 3.0.6 on 2021-05-25 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0053_sasbcompanylookup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sasbcompanylookup',
            options={'ordering': ('industry',)},
        ),
    ]
