# Generated by Django 3.0.6 on 2021-05-21 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0053_auto_20210521_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyassessment',
            name='report_reference_slug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
