# Generated by Django 2.0.1 on 2019-11-04 11:15

from django.db import migrations
from django.db.utils import OperationalError
from django.template.defaultfilters import slugify


def generate_fund_slugs(apps, schema_editor):
    assessments = apps.get_model("company", "CompanyAssessment")

    for assessment in assessments.objects.all():
        assessment.report_reference_slug = slugify(assessment.report_reference)
        assessment.save()
        assessment.save()

class Migration(migrations.Migration):

    dependencies = [
        ('company', '0054_companyassessment_report_reference_slug'),
    ]

    operations = [
        migrations.RunPython(generate_fund_slugs, reverse_code=migrations.RunPython.noop),
    ]