# Generated by Django 3.0.6 on 2021-05-25 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0055_assessment_slugify_reference'),
        ('company', '0053_merge_20210520_1437'),
        ('company', '0053_sasbcompanylookup'),
    ]

    operations = [
    ]
