# Generated by Django 3.0.6 on 2021-05-25 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0056_merge_20210525_0825'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sasbcompanylookup',
            options={'ordering': ('industry',)},
        ),
        migrations.AddField(
            model_name='companyassessment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.CompanyAssessment'),
        ),
    ]
