# Generated by Django 3.0.6 on 2021-05-25 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0057_auto_20210525_1011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyassessment',
            name='report_reference_slug',
        ),
    ]
