# Generated by Django 3.0.6 on 2021-05-25 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0058_remove_companyassessment_report_reference_slug'),
        ('company', '0054_auto_20210525_1157'),
    ]

    operations = [
    ]
