# Generated by Django 2.0.1 on 2019-11-04 11:15

from django.db import migrations
from django.db.utils import OperationalError
from django.template.defaultfilters import slugify


def unique_assessment_names(apps, schema_editor):
    pass
    assessments = apps.get_model("company", "CompanyAssessment")
    done_list = []
    for assessment in assessments.objects.filter(parent=None):
        children = assessments.objects.filter(parent=assessment)
        if assessment.report_name not in done_list:
            if children:
                for num, child in enumerate(children, start=1):
                    child.report_name = child.report_name + '_{}'.format(num)
                    child.save()
            else:
                same_name_assessments = assessments.objects.filter(report_name=assessment.report_name)
                if same_name_assessments:
                    for num, child in enumerate(same_name_assessments, start=1):
                        child.report_name = child.report_name + '_{}'.format(num)
                        child.save()
            
            done_list.append(assessment.report_name)
    not_done_assessments =  assessments.objects.all().exclude(report_name__in=done_list)

    if not_done_assessments:
        for assessment in not_done_assessments:
            if assessment.report_name not in done_list:
                if children:
                    for num, child in enumerate(children, start=1):
                        child.report_name = child.report_name + '_{}'.format(num)
                        child.save()
                else:
                    same_name_assessments = assessments.objects.filter(report_name=assessment.report_name)
                    if same_name_assessments:
                        for num, child in enumerate(same_name_assessments, start=1):
                            child.report_name = child.report_name + '_{}'.format(num)
                            child.save()
                done_list.append(assessment.report_name)


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0059_merge_20210525_1405'),
    ]

    operations = [
        migrations.RunPython(unique_assessment_names, reverse_code=migrations.RunPython.noop),
    ]