# Generated by Django 3.0.6 on 2021-06-01 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0060_make_assessment_names_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyassessment',
            name='report_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Report Name'),
        ),
    ]
