# Generated by Django 3.0.6 on 2021-06-02 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0061_auto_20210601_0902'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='industrytype',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='companyassessment',
            name='answered_optional',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
