# Generated by Django 3.0.6 on 2021-06-15 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0062_auto_20210602_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managementquestionanswerset',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
