# Generated by Django 3.0.6 on 2021-06-17 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20210611_1152'),
        ('company', '0063_auto_20210615_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyassessment',
            name='custom_risk_score',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Threshold'),
        ),
    ]
