# Generated by Django 3.0.6 on 2021-06-30 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0064_companyassessment_custom_risk_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managementquestionanswerset',
            name='insufficient',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='managementquestionanswerset',
            name='priority',
            field=models.BooleanField(default=False),
        ),
    ]
