# Generated by Django 3.0.6 on 2021-08-11 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0065_auto_20210630_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyassessment',
            name='company_description',
            field=models.TextField(blank=True, max_length=320, null=True),
        ),
    ]
