# Generated by Django 3.0.6 on 2021-08-16 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0066_auto_20210811_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyassessment',
            name='company_description',
            field=models.TextField(blank=True, max_length=270, null=True),
        ),
    ]
