# Generated by Django 3.0.6 on 2022-05-09 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0067_auto_20210816_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyassessment',
            name='client_reference',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='companyassessment',
            name='report_reference',
            field=models.CharField(blank=True, max_length=255, verbose_name='Report reference'),
        ),
    ]
