# Generated by Django 4.0.4 on 2022-06-20 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0068_auto_20220509_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyassessment',
            name='issue_extra_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
