# Generated by Django 3.0.6 on 2020-12-21 12:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0049_auto_20201113_1118'),
        ('riskfactor', '0046_riskfactorcategory_sort_order'),
        ('kpi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyPerformanceIndicator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_kpi', models.BooleanField(default=False)),
                ('detail', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('I', 'In progress'), ('A', 'Achieved'), ('N', 'Not achieved')], max_length=1, null=True)),
                ('commentary', models.TextField(blank=True, null=True)),
                ('aspect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riskfactor.RiskDataSet')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.CompanyAssessment')),
                ('related_standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kpi.RelatedStandard')),
                ('sdg_alignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kpi.SustainableDevelopmentGoal')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
