# Generated by Django 3.0.6 on 2020-12-22 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0050_auto_20201221_1429'),
        ('kpi', '0002_keyperformanceindicator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyperformanceindicator',
            name='assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.CompanyAssessment'),
        ),
    ]
