# Generated by Django 3.0.6 on 2020-12-22 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0003_auto_20201222_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyperformanceindicator',
            name='related_standard',
        ),
        migrations.AddField(
            model_name='keyperformanceindicator',
            name='related_standard',
            field=models.ManyToManyField(blank=True, to='kpi.RelatedStandard'),
        ),
        migrations.RemoveField(
            model_name='keyperformanceindicator',
            name='sdg_alignment',
        ),
        migrations.AddField(
            model_name='keyperformanceindicator',
            name='sdg_alignment',
            field=models.ManyToManyField(blank=True, to='kpi.SustainableDevelopmentGoal'),
        ),
    ]
