from django.urls import path

from . import (
    views,
    management_question_views,
    document_question_views,
    riskfactor_views,
    riskfactor_score_views,
    industry_score_views,
    upload_industry_scores,
    industry_views,
    company_views
)

urlpatterns = [
    path(
        '',
        views.StaffAdminView.as_view(),
        name='staff_admin_base'
    ),
    path('upload', views.UploadView.as_view(), name='upload'),
    path('upload-industry-scores', upload_industry_scores.UploadIndustryView.as_view(), name='upload_industry'),
    path(
        'confirm-upload/<slug:version_id>',
        views.confirm_upload,
        name='confirm_upload'
    ),
    path("file-download/<pk>", views.DownloadFile.as_view(), name="download_file"),
    path(
        'confirm-industry_upload',
        upload_industry_scores.publish_industry_values,
        name='publish_industry_values'
    ),
    path(
        'risk-scores',
        riskfactor_score_views.RiskFactorValueListView.as_view(),
        name='risk_factor_values'
    ),
    path(
        'riskfactor-values-list-table',
        riskfactor_score_views.RiskFactorValueTable,
        name='risk_factor_values_table'
    ),
    path(
        'risk-score/<pk>/',
        riskfactor_score_views.RiskFactorValueDetailView.as_view(),
        name='risk_factor_values_detail'
    ),
    path(
        'add-risk-factor/',
        riskfactor_views.RiskFactorCreateView.as_view(),
        name='risk_factor_add'
    ),
    path(
        'riskfactors/',
        riskfactor_views.RiskFactorListView.as_view(),
        name='riskfactors_list'
    ),
    path(
        'riskfactors-datatable',
        riskfactor_views.RiskFactorListDataTable,
        name='risk_factor_list_data_table'
    ),
    path(
        'riskfactor/<pk>/',
        riskfactor_views.RiskFactorDetailView.as_view(),
        name='risk_factor_detail'
    ),
    path(
        'riskfactor/delete/<pk>/',
        riskfactor_views.DeleteRiskFactor,
        name='risk_factor_delete'
    ),
    path(
        'document-questions',
        document_question_views.DocumentQuestionsListView.as_view(),
        name='document_questions_list'
    ),
    path(
        'document-questions-list-table',
        document_question_views.DocumentQuestionTable,
        name='document_questions_list_table'
    ),
    path(
        'document-question/<pk>/',
        document_question_views.DocumentQuestionDetailView.as_view(),
        name='document_question_detail'
    ),
    path(
        'document-question/create',
        document_question_views.DocumentQuestionCreateView.as_view(),
        name='document_question_create'
    ),
    path(
        'document-question/delete/<pk>/',
        document_question_views.DeleteDocumentQuestion,
        name='document_question_delete'
    ),
    path(
        'management-questions',
        management_question_views.ManagementQuestionsListView.as_view(),
        name='management_questions_list'
    ),
    path(
        'management-questions-list-table',
        management_question_views.ManagementQuestionTable,
        name='management_questions_list_table'
    ),
    path(
        'management-question/<pk>/',
        management_question_views.ManagementQuestionDetailView.as_view(),
        name='management_question_detail'
    ),
    path(
        'management-question/create',
        management_question_views.ManagementQuestionCreateView.as_view(),
        name='management_question_create'
    ),
    path(
        'management-question/delete/<pk>/',
        management_question_views.DeleteManagementQuestion,
        name='management_question_delete'
    ),
    path(
        'industry-risk-scores',
        industry_score_views.IndustryRiskValueListView.as_view(),
        name='industry_risk_factor_values'
    ),
    path(
        'industry-risk-score/<pk>/',
        industry_score_views.IndustryRiskFactorValueDetailView.as_view(),
        name='industry_risk_factor_values_detail'
    ),
    path(
        'industry-risk-scores-table',
        industry_score_views.IndustryRiskFactorValueTable,
        name='industry_risk_factor_values_table'
    ),
    path(
        'industries',
        industry_views.IndustryListView.as_view(),
        name='industries_list'
    ),
    path(
        'industry-table',
        industry_views.IndustryListTable,
        name='industries_list_table'
    ),
    path(
        'industry/<pk>/',
        industry_views.IndustryDetailView.as_view(),
        name='industry_detail'
    ),
    path(
        'industry/sasb-table-update/<pk>/',
        industry_views.UpdateSasb,
        name='industry_sasb_table_update'
    ),
    path(
        'industry/create',
        industry_views.IndustryCreateView.as_view(),
        name='industry_create'
    ),
    path(
        'industry/delete/<pk>/',
        industry_views.DeleteIndustry,
        name='industry_delete'
    ),
    path(
        'country_template/',
        views.dataCountryTemplate.as_view(),
        name='country_template_download'
    ),
    path(
        'companies',
        company_views.CompanyListView.as_view(),
        name='company_list'
    ),
    path(
        'company-table',
        company_views.CompanyTable,
        name='company_table'
    ),
    path(
        'company/<pk>/',
        company_views.CompanyDetailView.as_view(),
        name='company_detail'
    ),
    path(
        'toggle-permission',
        company_views.TogglePermission,
        name='toggle_permission'
    ),
    path(
        'sasb_update',
        industry_views.UpdateAllSasb,
        name='sasb_update'
    ),
    path(
        'sasb_create',
        industry_views.RecreateAllSasb,
        name='sasb_create'
    ),
]
