from django.urls import path

from . import views

urlpatterns = [
    path(
        'assessment/versions/<slug:slug>/',
        views.CompanyVersionListView.as_view(),
        name='company_version'
    ),
    path(
        'assessment/key-details',
        views.CompanyAssessmentKeyDetailsView.as_view(),
        name='company_assessment_key_detail'
    ),
    path(
        'assessment/key-details/<slug:slug>/',
        views.CompanyAssessmentKeyDetailsView.as_view(),
        name='company_assessment_key_detail'
    ),
    path(
        'assessment/industries/<slug:slug>/',
        views.CompanyIndustriesView.as_view(),
        name='company_assessment_industries'
    ),
    path(
        'assessment/company-footprint/<slug:slug>/',
        views.CompanyAssessmentCompanyFootprintView.as_view(),
        name='company_assessment_company_footprint'
    ),
    path(
        'assessment/esg-maturity-review/<slug:slug>/',
        views.CompanyAssessmentDocumentCheckListView.as_view(),
        name='company_assessment_document_checklist'
    ),
    path(
        'assessment/management-questions/<slug:slug>/',
        views.CompanyAssessmentManagementView.as_view(),
        name='company_management_questions'
    ),
    path(
        'assessment/recommendations/<slug:slug>/',
        views.CompanyAssessmentRecommendationsView.as_view(),
        name='company_recommendations'
    ),
    path(
        'assessment-resume/<slug:slug>/',
        views.Assessment_phase_redirect,
        name='assessment_resume'
    ),
    path(
        'industries-select/',
        views.Industry_select,
        name='industry_select'
    ),
    path(
        'industries-comparison-table/',
        views.Industry_table,
        name='industry_table'
    ),
    path(
        'geographic-comparison-table/',
        views.Geographic_table,
        name='geographic_table'
    ),
    path(
        'risk-description/',
        views.Risk_description,
        name='risk_description'
    ),
    path(
        'risk-options/',
        views.risk_options,
        name='risk_options'
    ),
    path(
        'initial-selected-risk-options/',
        views.initial_selected_risk_options,
        name='initial_selected_risk_options'
    ),
    path(
        'industry-options/',
        views.industry_options,
        name='industry_options'
    ),
    path(
        'management_csv/<slug:slug>/<str:optional>',
        views.management_csv,
        name='management_csv_download'
    ),
    path(
        'document_checklist_csv/<slug:slug>/<str:optional>',
        views.document_checklist_csv,
        name='document_checklist_download'
    ),
    path(
        'footprint_csv/',
        views.footprintCsv.as_view(),
        name='footprint_csv_download'
    ),
    path(
        'management_question_remove_question/<slug:slug>/',
        views.hide_management_question,
        name='remove_management_question'
    ),
    path(
        'risk_recommendations/',
        views.risk_recommendations,
        name='get_risk_recommendations'
    ),
    path(
        'calculate_inherent_risk/',
        views.inherent_risk,
        name='inherent_risk'
    ),
    path(
        'delete_assessment/<slug:slug>',
        views.assessment_delete,
        name='assessment_delete'
    ),
    path(
        'management_partial_save/',
        views.partial_save,
        name='management_partial_saveing'
    ),
    path(
        'toggle-assessment-industry/',
        views.assessment_add_remove_industry,
        name='toggle_assessment_industry'
    ),
    path(
        'sasb-company-check/',
        views.sasb_company_check,
        name='sasb_company_check'
    ),
    path(
        'custom-score-select/',
        views.custom_risk_score_select,
        name='custom_score_select'
    ),
]
