# Generated by Django 3.0.6 on 2020-05-27 11:41

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '__first__'),
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskDataSetVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('name', models.CharField(max_length=255, verbose_name='Risk Factor Version')),
                ('source', models.TextField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=1024, null=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Risk Factor Version',
                'ordering': ('-created_date',),
            },
        ),
        migrations.CreateModel(
            name='RiskFactorCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Category Name')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=255, populate_from=['name'], verbose_name='Category Code')),
            ],
            options={
                'verbose_name': 'Risk Factor Category',
                'verbose_name_plural': 'Risk Factor Categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='RiskDataSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Risk Factor Name')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=255, populate_from=['name'], verbose_name='Risk Factor Code')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('recommendation', models.TextField(blank=True)),
                ('reminder', models.BooleanField(blank=True, default=True)),
                ('update_status', models.PositiveIntegerField(choices=[(1, 'Up-to-date'), (2, 'Update required'), (3, 'Update pending')], default=1)),
                ('update_due', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('active_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riskfactor.RiskDataSetVersion', verbose_name='Category')),
                ('applications', models.ManyToManyField(related_name='riskfactors', to='core.Application')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riskfactor.RiskFactorCategory', verbose_name='Category')),
                ('versions', models.ManyToManyField(related_name='versions', to='riskfactor.RiskDataSetVersion')),
            ],
            options={
                'verbose_name': 'Risk Factor',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='CountryRisk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exposure', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('materiality', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='country.Country')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riskfactor.RiskDataSetVersion')),
            ],
            options={
                'verbose_name': 'Exposure/Materiality Score',
            },
        ),
    ]
