# Generated by Django 3.0.6 on 2020-05-27 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riskfactor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskdataset',
            name='active_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='riskfactor.RiskDataSetVersion', verbose_name='Category'),
        ),
    ]
