# Generated by Django 3.0.6 on 2020-05-29 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riskfactor', '0003_auto_20200528_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskdataset',
            name='active_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='riskfactor.RiskDataSetVersion', verbose_name='Active version'),
        ),
    ]
