# Generated by Django 3.0.6 on 2020-06-11 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskfactor', '0004_auto_20200529_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskdataset',
            name='abbreviated_recommendation',
            field=models.TextField(blank=True),
        ),
    ]
