# Generated by Django 3.0.6 on 2020-06-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskfactor', '0005_riskdataset_abbreviated_recommendation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countryrisk',
            name='exposure',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='countryrisk',
            name='materiality',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
