# Generated by Django 3.0.6 on 2020-06-12 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskfactor', '0006_auto_20200611_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskdataset',
            name='recommendation',
            field=models.TextField(blank=True, verbose_name='Default recommendation'),
        ),
    ]
