# Generated by Django 3.0.6 on 2020-06-12 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_industry'),
        ('riskfactor', '0007_auto_20200612_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialityRisk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materiality', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('dataset_version', models.ForeignKey(limit_choices_to={'relates_to': 'I'}, on_delete=django.db.models.deletion.CASCADE, to='riskfactor.RiskDataSetVersion')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Industry')),
            ],
            options={
                'verbose_name': 'Materiality Score',
                'unique_together': {('industry', 'dataset_version')},
            },
        ),
        migrations.CreateModel(
            name='IndustryRiskDataSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_version', models.ForeignKey(limit_choices_to={'relates_to': 'I'}, on_delete=django.db.models.deletion.CASCADE, to='riskfactor.RiskDataSetVersion')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Industry')),
            ],
            options={
                'unique_together': {('industry', 'dataset_version')},
            },
        ),
    ]
