# Generated by Django 3.0.6 on 2020-06-12 14:25

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('riskfactor', '0008_industryriskdataset_materialityrisk'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskDataSetSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Source')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=255, populate_from=['name'])),
                ('colour', models.CharField(max_length=6, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AlterModelOptions(
            name='countryrisk',
            options={'verbose_name': 'Exposure Score'},
        ),
        migrations.RemoveField(
            model_name='countryrisk',
            name='materiality',
        ),
    ]
