# Generated by Django 3.0.6 on 2020-06-12 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riskfactor', '0009_auto_20200612_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskdatasetversion',
            name='reference',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riskdatasetversion',
            name='relates_to',
            field=models.CharField(choices=[('C', 'Country'), ('I', 'Industry')], default='C', max_length=1),
        ),
        migrations.AlterField(
            model_name='riskdataset',
            name='active_version',
            field=models.ForeignKey(blank=True, limit_choices_to={'relates_to': 'C'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='riskfactor.RiskDataSetVersion', verbose_name='Active version'),
        ),
        migrations.AlterField(
            model_name='riskdataset',
            name='versions',
            field=models.ManyToManyField(limit_choices_to={'relates_to': 'C'}, related_name='versions', to='riskfactor.RiskDataSetVersion'),
        ),
        migrations.AlterField(
            model_name='riskdatasetversion',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='riskfactor.RiskDataSetSource'),
        ),
    ]
