# Generated by Django 3.0.6 on 2020-06-12 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riskfactor', '0010_auto_20200612_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='industryriskdataset',
            name='risk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='riskfactor.RiskDataSet'),
        ),
    ]
