# Generated by Django 3.0.6 on 2020-06-15 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riskfactor', '0011_industryriskdataset_risk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='industryriskdataset',
            name='risk',
        ),
    ]
