# Generated by Django 3.0.6 on 2020-06-15 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_industry'),
        ('riskfactor', '0013_industryriskdataset_risk_factor'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='industryriskdataset',
            unique_together={('industry', 'risk_factor')},
        ),
        migrations.AlterUniqueTogether(
            name='materialityrisk',
            unique_together=set(),
        ),
    ]
