# Generated by Django 3.0.6 on 2020-06-15 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_industry'),
        ('riskfactor', '0014_auto_20200615_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialityrisk',
            name='risk_factor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='riskfactor.RiskDataSet'),
        ),
        migrations.AlterUniqueTogether(
            name='industryriskdataset',
            unique_together={('industry', 'dataset_version')},
        ),
        migrations.RemoveField(
            model_name='industryriskdataset',
            name='risk_factor',
        ),
    ]
