# Generated by Django 3.0.6 on 2020-06-16 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskfactor', '0015_auto_20200615_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='industryriskdataset',
            name='versions',
            field=models.ManyToManyField(blank=True, limit_choices_to={'relates_to': 'I'}, null=True, related_name='industry_versions', to='riskfactor.RiskDataSetVersion'),
        ),
    ]
