# Generated by Django 3.0.6 on 2020-06-16 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riskfactor', '0016_industryriskdataset_versions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industryriskdataset',
            name='dataset_version',
            field=models.ForeignKey(blank=True, limit_choices_to={'relates_to': 'I'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='riskfactor.RiskDataSetVersion'),
        ),
    ]
