# Generated by Django 3.0.6 on 2020-06-16 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riskfactor', '0017_auto_20200616_1156'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='industryriskdataset',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='industryriskdataset',
            name='industry',
        ),
    ]
