# Generated by Django 3.0.6 on 2020-06-16 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskfactor', '0018_auto_20200616_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='industryriskdataset',
            name='name',
            field=models.CharField(default='industries', max_length=255),
            preserve_default=False,
        ),
    ]
