# Generated by Django 3.0.6 on 2020-06-16 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_industry'),
        ('riskfactor', '0019_industryriskdataset_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='industryriskdataset',
            name='name',
        ),
        migrations.AddField(
            model_name='industryriskdataset',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.Industry'),
        ),
    ]
