# Generated by Django 2.0.1 on 2019-11-04 11:15

from django.db import migrations
from django.db.utils import OperationalError

def set_null_source(apps, schema_editor):
    print("Change Closed groups to private")

    versions = apps.get_model("riskfactor", "RiskDataSetVersion")
    versions = versions.objects.all()
    if versions:
        for version in versions:
            version.source = None
            version.save()

class Migration(migrations.Migration):

    dependencies = [
        ('riskfactor', '0020_auto_20200616_1454'),
    ]

    operations = [
        migrations.RunPython(set_null_source, reverse_code=migrations.RunPython.noop),
    ]