# Generated by Django 3.0.6 on 2020-06-17 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riskfactor', '0021_set_source_null'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riskdatasetversion',
            name='source',
        ),
    ]
