# Generated by Django 3.0.6 on 2020-06-17 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riskfactor', '0022_remove_riskdatasetversion_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialityrisk',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='riskfactor.RiskDataSetSource'),
        ),
    ]
