# Generated by Django 3.0.6 on 2020-06-18 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskfactor', '0023_materialityrisk_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskdataset',
            name='update_status',
            field=models.CharField(choices=[('o', 'Up to date'), ('r', 'Update required'), ('p', 'Update pending')], default='o', max_length=1),
        ),
    ]
