# Generated by Django 3.0.6 on 2020-06-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskfactor', '0024_auto_20200618_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industryriskdataset',
            name='versions',
            field=models.ManyToManyField(limit_choices_to={'relates_to': 'I'}, related_name='industry_versions', to='riskfactor.RiskDataSetVersion'),
        ),
    ]
