# Generated by Django 3.0.6 on 2020-08-03 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskfactor', '0025_auto_20200618_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskdataset',
            name='pdf_description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
    ]
