# Generated by Django 3.0.6 on 2020-08-06 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskfactor', '0026_riskdataset_pdf_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskdataset',
            name='pdf_description',
            field=models.TextField(blank=True, verbose_name='Pdf Description'),
        ),
    ]
