# Generated by Django 3.0.6 on 2020-09-28 08:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('riskfactor', '0036_risk_version_pk_to_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskdataset',
            name='active_version',
            field=models.ForeignKey(blank=True, limit_choices_to={'relates_to': 'C'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='riskfactor.RiskDataSetVersion', verbose_name='Active version'),
        ),
        migrations.AlterField(
            model_name='riskdatasetversion',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
