# Generated by Django 3.0.6 on 2020-09-29 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('country', '__first__'),
        ('riskfactor', '0039_auto_20200928_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countryrisk',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='country.Country'),
        ),
    ]
