# Generated by Django 3.0.6 on 2020-10-22 14:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0047_auto_20201009_1104'),
        ('riskfactor', '0040_auto_20200929_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industryriskdataset',
            name='industry',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='company.Industry'),
            preserve_default=False,
        ),
    ]
