# Generated by Django 3.0.6 on 2020-10-26 15:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('riskfactor', '0041_auto_20201022_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskdatasetversion',
            name='file_obj',
            field=models.FileField(default=django.utils.timezone.now, upload_to='uploads/version_data/'),
            preserve_default=False,
        ),
    ]
