# Generated by Django 3.0.6 on 2020-10-26 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskfactor', '0042_riskdatasetversion_file_obj'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskdatasetversion',
            name='skew',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
