# Generated by Django 3.0.6 on 2020-10-26 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskfactor', '0043_riskdatasetversion_skew'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskdatasetversion',
            name='data_order',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
