# Generated by Django 3.0.6 on 2020-10-27 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskfactor', '0044_riskdatasetversion_data_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskdatasetversion',
            name='normalised_data',
            field=models.BooleanField(default=True),
        ),
    ]
