# Generated by Django 3.0.6 on 2020-12-17 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskfactor', '0045_riskdatasetversion_normalised_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskfactorcategory',
            name='sort_order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
